### ISSUE TITLE
How to use Sentry Tracing?

### ISSUE THREAD

**Issue by omidh28** [mentos1386/nest-raven#115]
Does anyone know how to configure Sentry Tracing in NestJS to allow monitoring performance?

**Comment by mentos1386** [comment]
It's not currently supported. We would have to implement/reuse what they provide for express https://github.com/getsentry/sentry-javascript/blob/master/packages/tracing/src/integrations/express.ts

**Comment by gulaandrij** [comment]
will you plan to add it? really needed feature

**Comment by Atralbus** [comment]
For those who may need it, we were able to get tracing logs in NestJS with this configuration;

```ts
import * as Sentry from '@sentry/node'
import * as Tracing from '@sentry/tracing'

...

const expressApp = app.getHttpAdapter().getInstance()

Sentry.init({
  ...,
  integrations: [
    new Tracing.Integrations.Mongo({
      useMongoose: true,
    }),
    new Sentry.Integrations.Http({ tracing: true }),
    new Tracing.Integrations.Express({
      app: expressApp,
    }),
  ],
})

expressApp.use(Sentry.Handlers.requestHandler())
expressApp.use(Sentry.Handlers.tracingHandler())
```

**Comment by gulaandrij** [comment]
can confirm that this solution works in my nestjs app

**Comment by mentos1386** [comment]
Closing this, as the @Atralbus solution is the way to go how to use tracing/performance with this library.
