### ISSUE TITLE
req is non-serializable

### ISSUE THREAD

**Issue by maksimkurb** [mentos1386/nest-raven#14]
`req` extra is `**non-serializable**`, so it should not be set as extra.

![image](https://user-images.githubusercontent.com/1351924/57574682-9c4bdf80-744e-11e9-824f-7b9efa2f8918.png)

Also I have very high memory and CPU consumption while this task (serialization of `req`) with results of crash of the app (`Allocation failed - JavaScript heap out of memory`). I have to say, that it happens not after first catched exception, but after second or third.
If I [comment out this line](https://github.com/mentos1386/nest-raven/blob/9ea75fc0dab0be0a3628af8d2ca8104b12f0006f/lib/raven.interceptor.ts#L39), all works perfectly.
To fix that, interceptor should set only some serializable and neccessary parameters of request (url/called action (if rpc))

P.S. error occured on http mvc website with express as nest backend.
P.P.S. I can PM you a video demonstation, if you want; I don't have time for creating demo repository right now, honestly

**Comment by mentos1386** [comment]
Hey, thanks for the report!
I'll reuse `@sentry/node` [parseRequest](https://github.com/getsentry/sentry-javascript/blob/master/packages/node/src/handlers.ts#L158) to fix this.

**Comment by maksimkurb** [comment]
Keep in mind, that `httpRequest` valiable can be null on GraphQL requests (and microservices), may be other parser is needed for such requests

**Comment by mentos1386** [comment]
@maksimkurb thanks for input on that. I have merged #10 which introduces [different capture methods depending on context](https://github.com/mentos1386/nest-raven/blob/master/lib/raven.interceptor.ts#L39).

Sadly we [can't yet automatically detect what context interceptor is in](https://github.com/nestjs/nest/issues/1581), so I'll add support for graphql and microservice to be provided as `context`. And add custom logic for them.

**Comment by smonv** [comment]
@mentos1386 Can you release a fix for this issue first? Seem like #15 progress quite slow.

**Comment by mentos1386** [comment]
@smonv merged and released as v5.0.0. Improvements, when i'll have time. Will be tracked in #17

**Comment by smonv** [comment]
@mentos1386 Thank for the release
