### ISSUE TITLE
Latest release 5.0.0 introduces too many dependencies around graphql

### ISSUE THREAD

**Issue by zenozen** [mentos1386/nest-raven#18]
It seems that graphql and related things like `@nestjs/graphql` is now part of `dependencies` instead of `devDependencies` or `optionalDependencies`. It would bloat the number of packages in any project. 

Is this intended?

**Comment by mentos1386** [comment]
`@nestjs/graphql` is needed for us to support GraphQL exceptions (https://github.com/mentos1386/nest-raven/blob/master/lib/raven.interceptor.ts#L13). 

But looking at all the `dependencies`, it think i could remove `apollo-server-express` and `graphql`. I'll look in to it.

**Comment by mentos1386** [comment]
@zenozen can you try #19? Initial tests look like it could maybe work, i'll do some more testing this week/weekend.

**Comment by zenozen** [comment]
Thanks for the fast response! 

The change looks ok.
What's the best way for me to try it out? 
I was just looking at the change on `yarn.lock` and found +600 lines, so I guess if that's not the case anymore, we should be good?

**Comment by eropple** [comment]
Shouldn't `@nestjs/graphql` be a peer dependency?
