### ISSUE TITLE
tap is deprecated

### ISSUE THREAD

**Issue by kayvaninvemo** [mentos1386/nest-raven#180]
`tap` with callback is deprecated, is there any plan to migrate to `catchError`?

https://github.com/mentos1386/nest-raven/blob/6ffd5e4d8790a87c2d3bdf045575d0488a2faadb/lib/raven.interceptor.ts#L44

**Comment by 9renpoto** [comment]
@kayvaninvemo Hello, is there any documentation or other links I should refer to here?

**Comment by kayvaninvemo** [comment]
@9renpoto  [here](https://github.com/ReactiveX/rxjs/blob/4fb5d7d35ed0e1be429b59312a5593dc371f8d1f/src/internal/operators/tap.ts#L11) you find the source code of Tap in RxJs. I also find [this](https://dzhavat.github.io/2019/02/17/deprecations-in-rxjs-v6-4-0.html) which might be helpful.

**Comment by 9renpoto** [comment]
thank you reply :)
I'll make a fix PR
