### ISSUE TITLE
Problems with graphql integration

### ISSUE THREAD

**Issue by volbrene** [mentos1386/nest-raven#29]
Hello, first of all nice/helpful package.

But I have problems to integrate your plugin in my graphql setup. I have use your plugin in a simple rest api nest js project and it works, but if I will sending a mutation or Query via graphql I will get the error "Cannot read property 'headers' of undefined"

Is it a bug in the sentry package or where?

Thanks for your help.

- volbrene

Modules: 
`.....
@Module({
  imports: [
    RavenModule,
    GraphQLModule.forRootAsync({
      useClass: GraphqlConfigService,
    })
  ],
  controllers: [],
  providers: [
    {
      provide: APP_INTERCEPTOR,
      useValue: new RavenInterceptor(),
    },
  ],
})
export class AppModule {}`
Error:

> {
>   "errors": [
>     {
>       "message": "Cannot read property 'headers' of undefined",
>       "locations": [
>         {
>           "line": 2,
>           "column": 3
>         }
>       ],
>       "path": [
>         "login"
>       ],
>       "extensions": {
>         "code": "INTERNAL_SERVER_ERROR",
>         "exception": {
>           "stacktrace": [
>             "TypeError: Cannot read property 'headers' of undefined",
>             "    at extractRequestData (/Users/volbrene/development/apollo-server/app/node_modules/@sentry/node/dist/handlers.js:70:24)",
>             "    at Object.parseRequest (/Users/volbrene/development/apollo-server/app/node_modules/@sentry/node/dist/handlers.js:172:61)",
>             "    at RavenInterceptor.captureHttpException (/Users/volbrene/development/apollo-server/app/node_modules/nest-raven/raven.interceptor.js:54:38)",
>             "    at /Users/volbrene/development/apollo-server/app/node_modules/nest-raven/raven.interceptor.js:32:50",
>             "    at Hub.withScope (/Users/volbrene/development/apollo-server/app/node_modules/@sentry/hub/dist/hub.js:100:13)",
>             "    at callOnHub (/Users/volbrene/development/apollo-server/app/node_modules/@sentry/minimal/dist/index.js:17:28)",
>             "    at Object.withScope (/Users/volbrene/development/apollo-server/app/node_modules/@sentry/minimal/dist/index.js:158:5)",
>             "    at /Users/volbrene/development/apollo-server/app/node_modules/nest-raven/raven.interceptor.js:30:24",
>             "    at TapSubscriber._error (/Users/volbrene/development/apollo-server/app/node_modules/rxjs/internal/operators/tap.js:69:28)",
>             "    at TapSubscriber.Subscriber.error (/Users/volbrene/development/apollo-server/app/node_modules/rxjs/internal/Subscriber.js:72:18)"
>           ]
>         }
>       }
>     }
>   ],
>   "data": null
> }

**Comment by 9renpoto** [comment]
related https://github.com/nestjs/graphql/issues/443

**Comment by JeyongOh-MAASASIA** [comment]
[Solution]
When you provide RavenInterceptor on module, you can give options like this.
```
providers: [
        {
            provide: APP_INTERCEPTOR,
            useValue: new RavenInterceptor({ context: 'GraphQL' }),
        }
]
```

**Comment by mentos1386** [comment]
@volbrene sorry for late reply, can you try what @JeyongOh-MAASASIA wrote? You can also look at this example https://github.com/mentos1386/nest-raven#graphql.

**Comment by volbrene** [comment]
It works, thank you :)
