### ISSUE TITLE
Recommended way of implementing mixed context global RavenInterceptors

### ISSUE THREAD

**Issue by dhritzkiv** [mentos1386/nest-raven#33]
I have a Nest server that includes Http controllers and a Graphql endpoint (as supplied by the Nest Graphql module). I would like to be able to have global intercepters for both (as I don't want to specify an interceptor for every single Graphql resolver).

However, when an HTTP error occurs, the NestInterceptor for Graphql is triggered, resulting in complaints about missing fieldName et al.

Is it possible to achieve something like this?

```ts
// API module
@Module({
  imports: [
      RavenModule,
  ],
  providers: [
    // ideally, this would handle ONLY http requests
    {
      provide: APP_INTERCEPTOR,
      useValue: new RavenInterceptor({
         context: "Http"
      }),
    },
    // and this would ONLY handle GraphQL requests
    {
      provide: APP_INTERCEPTOR,
      useValue: new RavenInterceptor({
         context: "GraphQL"
      }),
    },
  ],
})
export default ApiAppModule {}
```

Or is it possible to only apply the RavenInterceptor to the GraphQL module?

**Comment by mentos1386** [comment]
Not currently. #31 will add partial automated context detection. But not yet for graphql. That will still have to be worked on.

**Comment by mentos1386** [comment]
@dhritzkiv Can you try `nest-raven@6.0.0-aplha.1` pre-release. It includes couple of PR's that remove the need for `context` to be passed. It should allow you to have one interceptor handle all the requests.

**Comment by 9renpoto** [comment]
released
