### ISSUE TITLE
Maintainer Wanted

### ISSUE THREAD

**Issue by mentos1386** [mentos1386/nest-raven#39]
Hey all.

__I am looking for someone that is willing to push this project forward.__ Since i started this project, my focus shifted away from backend development and using Nest. Which resulted in me not using Nest in more than a year. That makes it hard for me to develop something that I'm not using. 

Anyone willing to take over, please write in the comments and we can talk about it. If you think you know someone with knowledge to take over, please share this with them.

Requirements are knowledge of Nest and Sentry. Good to have would be to have experience with maintaining of open source software, but even without that it can work out, i will still be available to assist and help.

@9renpoto would you be willing to take over?

**Comment by 9renpoto** [comment]
Hello !
I would love to use this library for production.

If you need a maintainer, please invite the following account to help!

https://github.com/9renpoto
https://www.npmjs.com/~9renpoto

thank you :)

**Comment by mentos1386** [comment]
Awesome, that solves this :)
