### ISSUE TITLE
Graphql error when I try to import RavenModule

### ISSUE THREAD

**Issue by Kannas24** [mentos1386/nest-raven#42]
```
import { RavenModule } from 'nest-raven';
import {GraphQLModule} from "@nestjs/graphql"

@Module({
  imports: [
   GraphQLModule.forRoot({
        typePaths: ['./**/*.graphql'],
    }),
    RavenModule,
  ]
  ,
  controllers: [AppController],
  providers: [],
})
export class AppModule {
}
```

Error : ../node_modules/graphql/jsutils/devAssert.js:13 throw new Error(message);
            Must provide Source. Received: undefined.

@nestjs/graph version : "^7.3.5"
nest-raven version : "^5.0.0"
graphql version : "^15.0.0"

**Comment by 9renpoto** [comment]
@Kannas24

[v5.0.0](https://github.com/mentos1386/nest-raven/releases/tag/v5.0.0) not support yet `@nestjs/graphql@^v7.0.0` 

We are preparing support for version v6 and above.
If you like, can you try it on the branch below?

`npm install mentos1386/nest-raven#build --save`

- refs: https://github.com/mentos1386/nest-raven/milestone/1?closed=1

Thank you :)

**Comment by 9renpoto** [comment]
fixed it https://github.com/mentos1386/nest-raven/issues/44#issuecomment-631748589
thank you report :)
