### ISSUE TITLE
6.0.0 alpha 1 npm release has wrong folder structure

### ISSUE THREAD

**Issue by dhritzkiv** [mentos1386/nest-raven#44]
I installed the latest alpha build (based on your comment in #33), but the module won't install properly.

This is the folder structure: <img width="583" alt="image" src="https://user-images.githubusercontent.com/1349865/82401457-d8cdf600-9a27-11ea-8e1b-7885f700882f.png">

Nothing in the package.json signifies what the main file is. Also, the test directory is being included when it doesn't need to be.

It looks like the build branch has since been updated to fix the issue, so perhaps it's time for a new alpha build on npm?

**Comment by mentos1386** [comment]
Hey @dhritzkiv. Thanks for reporting this. Can you try version `6.0.0-alpha.2`?

**Comment by dhritzkiv** [comment]
Works well! Thanks.

btw, the `next` npm alias still points at alpha.1

**Comment by 9renpoto** [comment]
Fixed it :)
thank you reporting

**Comment by sgarner** [comment]
This non-working package has also been published as [v6.0.0 (non-alpha) on npm](https://www.npmjs.com/package/nest-raven/v/6.0.0), so is coming through in automated upgrades. You may want to deprecate this version on npm to indicate that it shouldn't be used.
