### ISSUE TITLE
release new version with peerDependency @nestjs/common v9

### ISSUE THREAD

**Issue by albohlabs** [mentos1386/nest-raven#448]
Can you pls release a new version with `@nestjs/common` v9 as peer dependency.

**Comment by lws803** [comment]
Bump on this, are there any plans on upgrading to nestjs v9? 😮

**Comment by NikkiDelRosso** [comment]
I have a project wanting to use `nest-raven` that is waiting for this, as well.

**Comment by lws803** [comment]
Also, it seems like we have support for nestjs v9 already? 🤔 https://github.com/mentos1386/nest-raven/blame/c7c5310c11d767d62e4a52a73c2ff76f6913c66d/package.json#L47-L52 since it has been updated automatically by the chore bot.

Maybe all it'll take is to publish master branch 😄

**Comment by 9renpoto** [comment]
https://www.npmjs.com/package/nest-raven published new version
