### ISSUE TITLE
improve ci pipeline

### ISSUE THREAD

**Issue by mentos1386** [mentos1386/nest-raven#47]
- [ ] `test.yaml` should only be executed on `pull_request`
- [ ] `release.yaml` should be split in to `pre_release.yaml` that looks for tags `^v(\d+\.)?(\d+\.)?(\*|\d+)-alpha(\d+\.)?$` (and same for `beta`). This should push to `npm` on `next` tag
- [ ] `release.yaml` should only look for ``^v(\d+\.)?(\d+\.)?(\*|\d+)$` tags.

Can we on `*release.yaml` also publish changelog on github?

**Comment by 9renpoto** [comment]
I prefer https://github.com/lerna/lerna-changelog . its cute :)

It's easy to generate with some tool, ex https://github.com/semantic-release/release-notes-generator ? 🤔

**Comment by mentos1386** [comment]
I really like [semantic-release/semantic-release](https://github.com/semantic-release/semantic-release).

What do you think if we just use that for automated releasing (and changelog generation)?

**Comment by mentos1386** [comment]
Hey, @9renpoto as you are now doing releasing. Do you think we need this?

**Comment by 9renpoto** [comment]
Hello. The library is also calm, so it doesn't seem to be a high priority for now :)
