### ISSUE TITLE
ravenClient.install() not invoked

### ISSUE THREAD

**Issue by mjgp2** [mentos1386/nest-raven#5]
You need to call `ravenClient.install();` to complete installation

**Comment by mentos1386** [comment]
@mjgp2 Thanks for reporting this. It seams i missed it here https://github.com/mentos1386/nest-raven/blob/master/lib/raven.providers.ts#L9. Kinda weird that it worked when i tested it.

I'll try to fix it today or in the weekend. If you want you can also make a PR for it, shouldn't be that big of a change.

**Comment by mentos1386** [comment]
Sorry it took me this long to fix this. It's now released in v2.0.1!
