### ISSUE TITLE
How to ignore route?

### ISSUE THREAD

**Issue by yepMad** [mentos1386/nest-raven#544]
Hey,

I'm using Raven with the global RavenInterceptor. I would like to block a route from being tracked, both for Performance and for Issues. How can I do it?

**Comment by mentos1386** [comment]
Hm, for Issues you should check at [filtering](https://docs.sentry.io/platforms/node/configuration/filtering/). For Performance there might be something similar in [configuration](https://docs.sentry.io/platforms/node/performance/#configure). In any case, this is out of scope of this library.

One case that could improve the library, would be to extend the [filter function](https://github.com/mentos1386/nest-raven/blob/master/lib/raven.interfaces.ts#L9-L11) by providing the "context", so the filter could be enhanced with more logic..
