### ISSUE TITLE
Filter check is incorrect

### ISSUE THREAD

**Issue by gotenxds** [mentos1386/nest-raven#553]
https://github.com/mentos1386/nest-raven/blob/f6ae487058d626b0550c707515538a15acf5b19b/lib/raven.interceptor.ts#LL176C1-L178C8

This code is incorrect and will return false when the filter returns true and the type of the exception is the requested type

```!(exception instanceof type && (!filter || filter(exception)));```

```!(true && (true || true));``` -> ``` !(true)``` -> false

**Comment by 9renpoto** [comment]
@gotenxds The `shouldReport` function is used to control whether or not a report is sent to sentry.

The default is to send all reports ( return true ).
We have added a test so you can check it out ( #612 )
