### ISSUE TITLE
Does this package handle draining?

### ISSUE THREAD

**Issue by simplenotezy** [mentos1386/nest-raven#566]
As per documentation: https://docs.sentry.io/platforms/node/configuration/draining/

Or do you need to implement something like this?

```ts
import { Injectable, Logger, OnApplicationShutdown, OnModuleDestroy } from '@nestjs/common';
import * as Sentry from '@sentry/node';

@Injectable()
export class AppService implements OnApplicationShutdown, OnModuleDestroy {
  onModuleDestroy() {
    // eslint-disable-next-line @typescript-eslint/no-floating-promises
    Sentry.close(2000).then(() => {
      process.exit();
    });
  }

  onApplicationShutdown(signal: string) {
    Logger.log(`Application is shutting down! Signal: ${signal}`); // e.g. "SIGINT"
  }
}

**Comment by mentos1386** [comment]
It's not provided by this package. Yes, you should do something like:
```ts
import { Injectable, OnApplicationShutdown } from '@nestjs/common';
import * as Sentry from '@sentry/node';

@Injectable()
export class AppService implements OnApplicationShutdown {
  async onApplicationShutdown(signal: string): Promise<void> {
    await Sentry.close(2000)
  }
}
```

**Comment by simplenotezy** [comment]
Thanks for the reply @mentos1386 - but is onApplicationShutdown async? 

https://docs.nestjs.com/fundamentals/lifecycle-events#lifecycle-events-1

**Comment by mentos1386** [comment]
>When the application receives a termination signal it will call any registered onModuleDestroy(), beforeApplicationShutdown(), then onApplicationShutdown() methods (in the sequence described above) with the corresponding signal as the first parameter. **If a registered function awaits an asynchronous call (returns a promise), Nest will not continue in the sequence until the promise is resolved or rejected.**

https://docs.nestjs.com/fundamentals/lifecycle-events#application-shutdown

**Comment by simplenotezy** [comment]
Thanks! Makes sense.
