### ISSUE TITLE
Websocket Support

### ISSUE THREAD

**Issue by ryanpager** [mentos1386/nest-raven#9]
Question -- Does the module support exceptions thrown from Websocket event gateways? I have it setup just like you have it as a global interceptor; and it seems to not catch anything. Just trying to figure out if I am screwing something up or not. Appreciate it!

**Comment by mentos1386** [comment]
Hey @ryanpager sorry for late reply. I have totally forgot about the websocket gateways. I'll write some test cases tomorrow to try it out.

**Comment by mentos1386** [comment]
@ryanpager strangly it doesn't work with global interceptor, but it works fine with method or class wide interceptor. It could be a nestjs issue and not this library specifically. I'll open an issue on nest repository and link it here.

**Comment by ryanpager** [comment]
@mentos1386 I appreciate ya -- ill just add it as a class wide interceptor for now! Thanks a bunch for checking.

**Comment by mentos1386** [comment]
Not a bug. Global interceptors (and guards) aren't applied to gateways by design.
